import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import { type ReactNode } from 'react'
import Header from '@/components/organisms/Header/Header'
// import Footer from './components/organisms/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <StickyAlert text={alertMsg} variant="danger" /> */}
        <Header />
        <main id="page-content">{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  )
}
